In [ ]:
import pandas as pd
import numpy as np

In [9]:
path_forest_arr = 'examples/forest_arr.npy'

In [11]:
with open(path_forest_arr, 'rb') as np_fl:
    forest_arr = np.load(np_fl)

In [12]:
def find_closest(value, discrete_vals):
    idx = np.argmin(np.abs(discrete_vals - value))
    return discrete_vals[idx]

In [65]:
def make_labels_to_nums(df_col):
    unique_labels = df_col.sort_values().unique()
    label2num = {i:label for i,label in enumerate(unique_labels)}
    return label2num

In [15]:
df = pd.read_excel('examples/Kaggle_Sirio_Libanes-16features.xlsx')

In [66]:
col_maps = {}
for col in df.columns:
    col_maps[col] = make_labels_to_nums(df[col])

In [80]:
df_forest = pd.DataFrame(forest_arr, columns=df.columns)

In [81]:
discrete_values = np.array(list(col_maps['AGE_PERCENTIL'].keys()))
# normalize the values in the column AGE_PERCENTIL, by dividing by max value, then multiply by max of discrete values
df_forest['AGE_PERCENTIL'] = df_forest['AGE_PERCENTIL'].apply(lambda val: (val/max(df_forest['AGE_PERCENTIL']) * max(discrete_values)))
# df_forest['AGE_PERCENTIL'] = df_forest['AGE_PERCENTIL'].apply(lambda val: find_closest(val, discrete_values))

In [82]:
df_forest['AGE_PERCENTIL']

0       1.371148
1       6.907123
2       3.702102
3       4.999554
4       7.265955
          ...
1235    6.594819
1236    3.830221
1237    1.933227
1238    6.914181
1239    4.522556
Name: AGE_PERCENTIL, Length: 1240, dtype: float64

In [83]:
df_forest['AGE_PERCENTIL'] = df_forest['AGE_PERCENTIL'].apply(lambda val: find_closest(val, discrete_values))

In [84]:
df_forest['AGE_PERCENTIL'].unique()

array([1, 7, 4, 5, 6, 3, 2, 9, 8])

In [85]:
# using the dictionary col_maps['AGE_PERCENTIL'] to convert the values back to the original labels
df_forest['AGE_PERCENTIL'] = df_forest['AGE_PERCENTIL'].apply(lambda val: col_maps['AGE_PERCENTIL'][val])

In [86]:
df_forest['AGE_PERCENTIL']

0       20th
1       80th
2       50th
3       60th
4       80th
        ...
1235    80th
1236    50th
1237    30th
1238    80th
1239    60th
Name: AGE_PERCENTIL, Length: 1240, dtype: object

In [114]:
df

,PATIENT_VISIT_IDENTIFIER,AGE_ABOVE65,AGE_PERCENTIL,GENDER,DISEASE GROUPING 1,DISEASE GROUPING 2,DISEASE GROUPING 3,DISEASE GROUPING 4,DISEASE GROUPING 5,DISEASE GROUPING 6,HTN,IMMUNOCOMPROMISED,OTHER,BLOODPRESSURE_DIASTOLIC_MEAN,BLOODPRESSURE_SISTOLIC_MEAN,ICU
0,0,1,60th,0,0,0,0,0,1,1,0,0,1,0.086420,-0.230769,0
1,0,1,60th,0,0,0,0,0,1,1,0,0,1,0.333333,-0.230769,0
2,0,1,60th,0,0,0,0,0,1,1,0,0,1,-0.243021,-0.338537,1
3,1,1,90th,1,0,0,0,0,0,0,1,1,1,-0.283951,-0.046154,1
4,1,1,90th,1,0,0,0,0,0,0,1,1,1,-0.407407,0.892308,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1235,384,0,50th,1,0,0,0,0,0,0,0,0,1,0.012346,-0.292308,0
1236,384,0,50th,1,0,0,0,0,0,0,0,0,1,0.086420,-0.384615,0
1237,384,0,50th,1,0,0,0,0,0,0,0,0,1,0.086420,-0.230769,0
1238,384,0,50th,1,0,0,0,0,0,0,0,0,1,0.209877,-0.384615,0
1239,384,0,50th,1,0,0,1,0,0,0,0,0,1,-0.185185,-0.539103,0

In [88]:
df['DISEASE GROUPING 2'].unique()

array([0, 1])

In [89]:
discrete_values = np.array(list(col_maps['GENDER'].keys()))
df_forest['GENDER'] = df_forest['GENDER'].apply(lambda val: (val/max(df_forest['GENDER']) * max(discrete_values)))

In [90]:
df_forest['GENDER'] = df_forest['GENDER'].apply(lambda val: find_closest(val, discrete_values))

In [91]:
df_forest['GENDER'] = df_forest['GENDER'].apply(lambda val: col_maps['GENDER'][val])

In [92]:
df_forest.head()

,PATIENT_VISIT_IDENTIFIER,AGE_ABOVE65,AGE_PERCENTIL,GENDER,DISEASE GROUPING 1,DISEASE GROUPING 2,DISEASE GROUPING 3,DISEASE GROUPING 4,DISEASE GROUPING 5,DISEASE GROUPING 6,HTN,IMMUNOCOMPROMISED,OTHER,BLOODPRESSURE_DIASTOLIC_MEAN,BLOODPRESSURE_SISTOLIC_MEAN,ICU
0,57.058721,0.008249,20th,0,1.034724,0.000611,-0.002636,-0.000759,0.982486,1.019868,0.000770,-0.001881,1.016347,-0.173055,-0.748683,0.001878
1,67.108971,-0.005100,80th,1,-0.008273,0.007686,-0.008612,0.004132,0.993894,-0.004540,0.012475,0.001858,1.032986,-0.109148,-0.167722,0.011431
2,59.141090,0.992882,50th,1,-0.004041,-0.002194,-0.017654,0.004366,0.964639,0.002206,0.007362,-0.002388,1.007571,-0.567682,-0.503241,0.004096
3,187.685210,-0.006572,60th,0,0.902088,-0.004007,-0.017534,0.003763,0.000719,0.947037,0.978744,0.005928,-0.022345,0.131017,-0.314843,-0.009925
4,193.385677,1.002278,80th,0,1.027558,0.009590,0.005564,-0.003284,0.008259,-0.001294,0.001361,0.001357,0.027196,0.112493,-0.440642,0.008797

In [93]:
def discretize_column(df, col_name, col_maps):
    discrete_values = np.array(list(col_maps[col_name].keys()))
    df[col_name] = df[col_name].apply(lambda val: (val/max(df[col_name]) * max(discrete_values)))
    df[col_name] = df[col_name].apply(lambda val: find_closest(val, discrete_values))
    df[col_name] = df[col_name].apply(lambda val: col_maps[col_name][val])
    return df

In [109]:
columns_of_interest = ['AGE_ABOVE65',
                       'PATIENT_VISIT_IDENTIFIER',
                       'GENDER',
                       'ICU',
                       'AGE_PERCENTIL',
                       'DISEASE GROUPING 1',
                        'DISEASE GROUPING 2',
                        'DISEASE GROUPING 3',
                        'DISEASE GROUPING 4',
                        'DISEASE GROUPING 5',
                        'DISEASE GROUPING 6',
                        'HTN',
                        'IMMUNOCOMPROMISED',
                        'OTHER']

In [110]:
df_forest = pd.DataFrame(forest_arr, columns=df.columns)

In [111]:
# apply the discretize_column function to all columns of interest in the dataframe df_forest
for col in columns_of_interest:
    df_forest = discretize_column(df_forest, col, col_maps)

In [112]:
df_forest.head()

,PATIENT_VISIT_IDENTIFIER,AGE_ABOVE65,AGE_PERCENTIL,GENDER,DISEASE GROUPING 1,DISEASE GROUPING 2,DISEASE GROUPING 3,DISEASE GROUPING 4,DISEASE GROUPING 5,DISEASE GROUPING 6,HTN,IMMUNOCOMPROMISED,OTHER,BLOODPRESSURE_DIASTOLIC_MEAN,BLOODPRESSURE_SISTOLIC_MEAN,ICU
0,60,0,20th,0,1,0,0,0,1,1,0,0,1,-0.173055,-0.748683,0
1,71,0,80th,1,0,0,0,0,1,0,0,0,1,-0.109148,-0.167722,0
2,63,1,50th,1,0,0,0,0,1,0,0,0,1,-0.567682,-0.503241,0
3,200,0,60th,0,1,0,0,0,0,1,1,0,0,0.131017,-0.314843,0
4,206,1,80th,0,1,0,0,0,0,0,0,0,0,0.112493,-0.440642,0

In [113]:
col_maps['PATIENT_VISIT_IDENTIFIER']

{0: 0,
 1: 1,
 2: 2,
 3: 3,
 4: 4,
 5: 5,
 6: 6,
 7: 7,
 8: 8,
 9: 9,
 10: 10,
 11: 11,
 12: 12,
 13: 13,
 14: 14,
 15: 15,
 16: 16,
 17: 17,
 18: 18,
 19: 19,
 20: 20,
 21: 21,
 22: 22,
 23: 23,
 24: 24,
 25: 25,
 26: 26,
 27: 27,
 28: 28,
 29: 29,
 30: 30,
 31: 31,
 32: 32,
 33: 33,
 34: 34,
 35: 35,
 36: 36,
 37: 37,
 38: 38,
 39: 39,
 40: 40,
 41: 41,
 42: 42,
 43: 43,
 44: 44,
 45: 45,
 46: 46,
 47: 47,
 48: 48,
 49: 49,
 50: 50,
 51: 51,
 52: 52,
 53: 53,
 54: 54,
 55: 55,
 56: 56,
 57: 57,
 58: 58,
 59: 59,
 60: 60,
 61: 61,
 62: 62,
 63: 63,
 64: 64,
 65: 65,
 66: 66,
 67: 67,
 68: 68,
 69: 69,
 70: 70,
 71: 71,
 72: 72,
 73: 73,
 74: 74,
 75: 75,
 76: 76,
 77: 77,
 78: 78,
 79: 79,
 80: 80,
 81: 81,
 82: 82,
 83: 83,
 84: 84,
 85: 85,
 86: 86,
 87: 87,
 88: 88,
 89: 89,
 90: 90,
 91: 91,
 92: 92,
 93: 93,
 94: 94,
 95: 95,
 96: 96,
 97: 97,
 98: 98,
 99: 99,
 100: 100,
 101: 101,
 102: 102,
 103: 103,
 104: 104,
 105: 105,
 106: 106,
 107: 107,
 108: 108,
 109: 109,
 110: 110,
 111: 111,
 112: 112,
 113: 113,
 114: 114,
 115: 115,
 116: 116,
 117: 117,
 118: 118,
 119: 119,
 120: 120,
 121: 121,
 122: 122,
 123: 123,
 124: 124,
 125: 125,
 126: 126,
 127: 127,
 128: 128,
 129: 129,
 130: 130,
 131: 131,
 132: 132,
 133: 133,
 134: 134,
 135: 135,
 136: 136,
 137: 137,
 138: 138,
 139: 139,
 140: 140,
 141: 141,
 142: 142,
 143: 143,
 144: 144,
 145: 145,
 146: 146,
 147: 147,
 148: 148,
 149: 149,
 150: 150,
 151: 151,
 152: 152,
 153: 153,
 154: 154,
 155: 155,
 156: 156,
 157: 157,
 158: 158,
 159: 159,
 160: 160,
 161: 161,
 162: 162,
 163: 163,
 164: 164,
 165: 165,
 166: 166,
 167: 167,
 168: 168,
 169: 169,
 170: 170,
 171: 171,
 172: 172,
 173: 173,
 174: 174,
 175: 175,
 176: 176,
 177: 177,
 178: 178,
 179: 179,
 180: 180,
 181: 181,
 182: 182,
 183: 183,
 184: 184,
 185: 185,
 186: 186,
 187: 187,
 188: 188,
 189: 189,
 190: 190,
 191: 191,
 192: 192,
 193: 193,
 194: 194,
 195: 195,
 196: 196,
 197: 197,
 198: 198,
 199: 200,
 200: 201,
 201: 202,
 202: 203,
 203: 204,
 204: 205,
 205: 206,
 206: 207,
 207: 208,
 208: 209,
 209: 210,
 210: 211,
 211: 212,
 212: 213,
 213: 214,
 214: 215,
 215: 216,
 216: 217,
 217: 218,
 218: 219,
 219: 220,
 220: 221,
 221: 222,
 222: 223,
 223: 224,
 224: 225,
 225: 226,
 226: 227,
 227: 228,
 228: 229,
 229: 230,
 230: 231,
 231: 232,
 232: 233,
 233: 234,
 234: 235,
 235: 236,
 236: 237,
 237: 238,
 238: 239,
 239: 240,
 240: 241,
 241: 242,
 242: 243,
 243: 244,
 244: 245,
 245: 246,
 246: 247,
 247: 248,
 248: 249,
 249: 250,
 250: 251,
 251: 252,
 252: 253,
 253: 254,
 254: 255,
 255: 256,
 256: 257,
 257: 258,
 258: 259,
 259: 260,
 260: 261,
 261: 262,
 262: 263,
 263: 264,
 264: 265,
 265: 266,
 266: 267,
 267: 268,
 268: 269,
 269: 270,
 270: 271,
 271: 272,
 272: 273,
 273: 274,
 274: 275,
 275: 276,
 276: 277,
 277: 278,
 278: 279,
 279: 280,
 280: 281,
 281: 282,
 282: 283,
 283: 284,
 284: 285,
 285: 286,
 286: 287,
 287: 288,
 288: 289,
 289: 290,
 290: 291,
 291: 292,
 292: 293,
 293: 294,
 294: 295,
 295: 296,
 296: 297,
 297: 298,
 298: 299,
 299: 300,
 300: 301,
 301: 302,
 302: 303,
 303: 304,
 304: 305,
 305: 306,
 306: 307,
 307: 308,
 308: 309,
 309: 310,
 310: 311,
 311: 312,
 312: 313,
 313: 314,
 314: 315,
 315: 316,
 316: 317,
 317: 318,
 318: 319,
 319: 320,
 320: 321,
 321: 322,
 322: 323,
 323: 324,
 324: 325,
 325: 326,
 326: 327,
 327: 328,
 328: 329,
 329: 330,
 330: 331,
 331: 332,
 332: 333,
 333: 334,
 334: 335,
 335: 336,
 336: 337,
 337: 338,
 338: 339,
 339: 340,
 340: 341,
 341: 342,
 342: 343,
 343: 344,
 344: 345,
 345: 346,
 346: 347,
 347: 348,
 348: 349,
 349: 350,
 350: 351,
 351: 352,
 352: 353,
 353: 354,
 354: 355,
 355: 356,
 356: 357,
 357: 358,
 358: 359,
 359: 360,
 360: 361,
 361: 362,
 362: 363,
 363: 364,
 364: 365,
 365: 366,
 366: 367,
 367: 368,
 368: 369,
 369: 370,
 370: 371,
 371: 372,
 372: 373,
 373: 374,
 374: 375,
 375: 376,
 376: 377,
 377: 378,
 378: 379,
 379: 380,
 380: 381,
 381: 382,
 382: 383,
 383: 384}